### ISSUE TITLE
deletes non-prefixed statements after changing value

### ISSUE THREAD

**Issue by stereonom** [wbond/sublime_prefixr#22]
When I have for example:

``` css
div {
    margin: 20px;
    padding: 10px;
    transition: 1s all;
}
```

it gets correctly prefixed to:

``` css
div {
    margin: 20px;
    padding: 10px;
    -webkit-transition: 1s all;
    -moz-transition: 1s all;
    -o-transition: 1s all;
    -ms-transition: 1s all;
    transition: 1s all;
}
```

Now I change the last row from "transition: 1s all;" to "transition: 5s all;" and hit the prefix commando again.
The result is:

``` css
div {
    -webkit-transition: 5s all;
    -moz-transition: 5s all;
    -o-transition: 5s all;
    -ms-transition: 5s all;
    transition: 5s all;
}
```

It killed the margin and the padding statements.
I tried a few other tests and every time the statements before the prefixed ones get killed.

Hope you can fix this soon.
