### ISSUE TITLE
When running prefixr multiple times, some styles may disappear

### ISSUE THREAD

**Issue by ChezFre** [wbond/sublime_prefixr#4]
I started out with the following code block:

```
#wrapper {
background-color: rgb(200,180,255);
border-radius: 10px;
}
```

Running prefixr once gave me prefixes for -webkit and -moz, running it again removed the background-color style.

**Comment by gornostal** [comment]
I have similar issue.
Only in my case styles disappear every time when I run prefixr :(

**Comment by gornostal** [comment]
I figured out that it happens only when I select one css property and then run prefixr

**Comment by ninnypants** [comment]
Same issue here in Build 2181

It seems to be that if you run the command on an item that has been prefixed it removes the rest of the rules for that selector. So this:

``` css
div{
    background: #000;
    transform: rotate(20deg);
}
```

Turns into:

``` css
div{
    background: #000;
    -webkit-transform: rotate(20deg);
    -moz-transform: rotate(20deg);
    -o-transform: rotate(20deg);
    -ms-transform: rotate(20deg);
    transform: rotate(20deg);
}
```

Then into:

``` css
div{
    -webkit-transform: rotate(20deg);
    -moz-transform: rotate(20deg);
    -o-transform: rotate(20deg);
    -ms-transform: rotate(20deg);
    transform: rotate(20deg);
}
```
