### ISSUE TITLE
Support for rgba Colours?

### ISSUE THREAD

**Issue by G0dwin** [wbond/sublime_prefixr#8]
Not exactly a prefix, but it would be extremely handy for Prefixr to add cross browser support for rgba values, that is changing code such as:

``` css
div.red {
    background-color: rgba(255, 0, 0, 0.5);
}
```

to something like:

``` css
div.red {
    background-color: rgb(255, 0, 0);
    background-color: rgba(255, 0, 0, 0.5);
}
```

to make the page still somewhat compatible with IE8-.

Thanks!
